spring:
  application:
    name: lottery
  datasource:
    url : jdbc:mysql://localhost:3306/lottery?verifyServerCertificate=false&useSSL=false
    username : 
    password : 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database : MYSQL 
    show-sql : true
    hibernate:
     ddl-auto : update
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect 
server:
  port: 8080
